CREATE TABLE `vih_form` (
  `id_vih_form` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del formulario de VIH/SIDA',
  `id_tipo_identidad` int(11) DEFAULT NULL,
  `numero_identificacion` varchar(30) DEFAULT NULL,
  `per_asegurado` int(1) DEFAULT NULL COMMENT '1: asegurado, 2: no asegurado',
  `per_edad` int(3) DEFAULT '0' COMMENT 'Edad de la persona fallecida',
  `per_tipo_edad` int(1) NOT NULL COMMENT 'Tipo de dato de edad:n0 = No Daton1 = Añosn2 = Mesesn3 = Díasn',
  `per_id_corregimiento` int(11) NOT NULL COMMENT 'Corregimiento en donde vive la persona',
  `per_localidad` varchar(100) DEFAULT NULL COMMENT 'Localidad en donde vive la persona',
  `per_estado_civil` int(1) DEFAULT NULL COMMENT '1:soltero 2:casado 3:unido 4:divorciado 5:NE',
  `comp_its_ultimo` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido',
  `comp_its_ulcerativa` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido ITS ulcerativa',
  `comp_edad_inicio_sexual` int(3) DEFAULT NULL COMMENT 'Edad de inicio de vida sexual activa',
  `comp_uso_condon` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido',
  `comp_trabajador_sexual` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido',
  `comp_donante_sangre` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido',
  `comp_donante_fecha` int(4) DEFAULT NULL COMMENT 'Anio de la ultima donacion de sangre',
  `comp_donante_instalacion` varchar(100) DEFAULT NULL COMMENT 'Nombre de la instalacion donde realizo la ultima donacion de sangre',
  `comp_per_preso` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desc persona privada de la libertad',
  `comp_embarazada` int(1) DEFAULT NULL COMMENT '1:si 2:no 0:desconocido',
  `comp_emb_3` int(4) DEFAULT NULL COMMENT 'Anio del embarazo 3',
  `comp_emb_2` int(4) DEFAULT NULL COMMENT 'Anio del embarazo 2',
  `comp_emb_1` int(4) DEFAULT NULL COMMENT 'Anio del embarazo 1',
  `comp_emb_captada` int(1) DEFAULT '4' COMMENT '1:>20 sem 2:<20 3:puerperino 4:desc',
  `comp_fecha_parto` date DEFAULT NULL COMMENT 'Fecha posible del parto',
  `cond_vih` int(1) DEFAULT NULL COMMENT '1:marcado caso de VIH',
  `cond_fecha_vih` date DEFAULT NULL COMMENT 'Fecha de diagnostico del caso de VIH',
  `cond_edad_vih` int(3) DEFAULT NULL COMMENT 'Edad del paciente en el momento que le diagnosticaron VIH: 999 Desconoce',
  `cond_sida` int(1) DEFAULT NULL COMMENT '1:marcado caso de SIDA',
  `cond_fecha_sida` date DEFAULT NULL COMMENT 'Fecha de diagnostico del caso de SIDA',
  `cond_edad_sida` int(3) DEFAULT NULL COMMENT 'Edad del paciente en el momento que le diagnosticaron SIDA: 999 Desconoce',
  `cond_sobrevida` varchar(50) DEFAULT NULL COMMENT 'La sobrevida se calcula con la resta de la fecha de diagnostico entre VIH y Sida',
  `cond_condicion_paciente` int(1) DEFAULT NULL COMMENT '1:vivo 2:muerto 3:desconoce, condicion actual del paciente',
  `cond_fecha_defuncion` date DEFAULT NULL COMMENT 'Fecha de la defuncion del paciente',
  `cond_sobrevida_sida` varchar(50) DEFAULT NULL COMMENT 'La sobrevida se calcula con la resta de la fecha de diagnostico Sida y la de defuncion',
  `cond_lugar_diagnostico` varchar(100) DEFAULT NULL COMMENT 'Nombre del lugar donde diagnosticaron el caso del paciente',
  `cond_lugar_diagnostico_sida` varchar(100) DEFAULT NULL COMMENT 'Nombre del lugar donde diagnosticaron el caso DE SIDA del paciente',
  `id_un` int(11) DEFAULT NULL COMMENT 'Código de la unidad notificadora',
  `unidad_disponible` int(1) DEFAULT NULL COMMENT '1:marcado no dispoible la unidad notificadora',
  `nombre_notifica` varchar(100) CHARACTER SET cp1250 DEFAULT NULL COMMENT 'Nombre de la persona que notifica',
  `fecha_notificacion` date DEFAULT NULL COMMENT 'Fecha en que se notifica el caso de VIH/SIDA',
  `semana_epi` int(11) NOT NULL COMMENT 'Semana epidemiológica',
  `anio` int(6) NOT NULL COMMENT 'Año de la semana epidemiológica',
  `nombre_registra` varchar(45) NOT NULL COMMENT 'Nombre de la persona que registra el formulario',
  `fecha_formulario` date NOT NULL COMMENT 'Fecha en que se llena el formulario',
  `silab` int(1) DEFAULT NULL COMMENT 'Identificador de la muestra si biene de SILAB',
  `cond_id_un_defuncion` int(11) DEFAULT NULL COMMENT 'codigo global de la muestra que viene de SILAB',
  `cond_otro_defuncion` varchar(100) DEFAULT NULL COMMENT 'Otro nombre de la unidad notificadora, se usa mucho cuando vienen de SILAB',
  `mue_id` int(11) DEFAULT NULL COMMENT 'Identificador de la muestra si biene de SILAB',
  `codigo_global` varchar(30) DEFAULT NULL COMMENT 'codigo global de la muestra que viene de SILAB',
  `otro_nombre_un` varchar(100) DEFAULT NULL COMMENT 'Otro nombre de la unidad notificadora, se usa mucho cuando vienen de SILAB',
  `epiInfo` int(1) DEFAULT '0' COMMENT '1: viene de EpiInfo y esta incompleto 2:EpiInfo actualizado 0: esta completo',
  `razon_sida` int(1) DEFAULT NULL,
  `nombre_notifica_sida` varchar(100) DEFAULT NULL,
  `fecha_notificacion_sida` date DEFAULT NULL,
  `observaciones` text,
  `tar` int(11) DEFAULT NULL,
  `fecha_tar` date DEFAULT NULL,
  `comp_its_sifilis` int(11) DEFAULT NULL,
  `comp_its_gonorrea` int(11) DEFAULT NULL,
  `comp_its_hepatitisb` int(11) DEFAULT NULL,
  `comp_its_hepatitisc` int(11) DEFAULT NULL,
  `comp_its_otras` int(11) DEFAULT NULL,
  `transexual` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_vih_form`),
  UNIQUE KEY `uk_vih_persona` (`id_tipo_identidad`,`numero_identificacion`),
  KEY `fk_vih_un` (`id_un`),
  KEY `fk_vih_corregimiento` (`per_id_corregimiento`),
  KEY `fk_vih_tipo_identificacion` (`id_tipo_identidad`),
  KEY `index_numero_identifica` (`numero_identificacion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla principal del formnualario de VIH/SIDA';

CREATE TABLE `vih_enfermedad_oportunista` (
  `id_vih_form` int(11) NOT NULL DEFAULT '0' COMMENT 'Identificador del formulario de VIH/SIDA',
  `id_evento` int(11) NOT NULL DEFAULT '0' COMMENT 'Identificador del evento CIE10',
  PRIMARY KEY (`id_vih_form`,`id_evento`),
  UNIQUE KEY `uk_vih_enfermedad_oportunista` (`id_vih_form`,`id_evento`),
  KEY `fk_vih_enfemerdad_form` (`id_vih_form`),
  KEY `fk_vih_evento` (`id_evento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla de rel del formnualario de VIH/SIDA con enfermedades o';

CREATE TABLE `vih_factor_riesgo` (
  `id_factor_riesgo` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del formulario de VIH/SIDA',
  `id_vih_form` int(11) DEFAULT NULL COMMENT 'Identificador del formulario de VIH/SIDA',
  `id_grupo_factor` int(11) DEFAULT NULL COMMENT 'Identificador del grupo de factor de reisgo',
  `id_factor` int(11) DEFAULT NULL COMMENT 'Identificador del factor de riesgo',
  PRIMARY KEY (`id_factor_riesgo`),
  UNIQUE KEY `uk_vih_factor_riesgo` (`id_vih_form`,`id_grupo_factor`,`id_factor`),
  KEY `fk_vih_form` (`id_vih_form`),
  KEY `fk_vih_grupo_factor` (`id_grupo_factor`),
  KEY `fk_vih_factor` (`id_factor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla de rel del formnualario de VIH/SIDA con el factor de r';

CREATE TABLE `vih_form_embarazo` (
  `id_vih_form_embarazo` int(30) NOT NULL AUTO_INCREMENT,
  `id_vih_form` int(11) DEFAULT NULL,
  `captada` int(11) DEFAULT NULL,
  `anio` int(11) DEFAULT NULL,
  `fecha_parto` date DEFAULT NULL,
  PRIMARY KEY (`id_vih_form_embarazo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vih_form_nino` (
  `id_vih_form_nino` int(30) NOT NULL AUTO_INCREMENT,
  `id_vih_form` int(11) NOT NULL,
  `termino_embarazo` int(1) DEFAULT NULL,
  `numero_cedula` varchar(45) DEFAULT NULL,
  `nombre` varchar(45) DEFAULT NULL,
  `apellido` varchar(45) DEFAULT NULL,
  `nacimiento` date DEFAULT NULL,
  `sexo` varchar(45) DEFAULT NULL,
  `pcr1` int(1) DEFAULT NULL,
  `pcr1_fecha` date DEFAULT NULL,
  `pcr2` int(1) DEFAULT NULL,
  `pcr2_fecha` date DEFAULT NULL,
  `estado` int(1) DEFAULT NULL,
  PRIMARY KEY (`id_vih_form_nino`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vih_muestra_prueba_silab` (
  `id_vih_muestra_prueba_silab` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del formulario',
  `id_vih_form` int(11) NOT NULL COMMENT 'Identificador del formulario muestras de lab silab',
  `id_muestra` int(11) NOT NULL COMMENT 'Identificador de la muestra en SILAB',
  `nombre_prueba` varchar(100) DEFAULT NULL COMMENT 'Nombre de la prueba',
  `resultado_prueba` varchar(45) DEFAULT NULL COMMENT 'Resultado de la prueba',
  `fecha_prueba` varchar(45) DEFAULT NULL COMMENT 'Fecha de la prueba',
  `Comentario_prueba` varchar(45) DEFAULT NULL COMMENT 'Comentarios de la prueba',
  PRIMARY KEY (`id_vih_muestra_prueba_silab`),
  KEY `fk_vih_form` (`id_vih_form`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla de relacion entre las muestras de laboratorio de silab';

CREATE TABLE `vih_muestra_silab` (
  `id_vih_muestra_silab` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del formulario',
  `id_vih_form` int(11) NOT NULL COMMENT 'Identificador del formulario VIH',
  `id_muestra` int(11) NOT NULL COMMENT 'Identificador de la muestra en SILAB',
  `codigo_global` varchar(45) DEFAULT NULL COMMENT 'Codigo Global de la muestra',
  `codigo_correlativo` varchar(45) DEFAULT NULL COMMENT 'Codigo Correlativo de la muestra',
  `tipo_muestra` varchar(45) DEFAULT NULL COMMENT 'Tipo de muestra',
  `fecha_inicio_sintoma` varchar(45) DEFAULT NULL COMMENT 'Fecha de inicio de sintomas',
  `fecha_toma` varchar(45) DEFAULT NULL COMMENT 'Fecha toma',
  `fecha_recepcion` varchar(45) DEFAULT NULL COMMENT 'Fecha recepcion',
  `unidad_notificadora` varchar(45) DEFAULT NULL COMMENT 'Unidad notificadora',
  `estado_muestra` varchar(45) DEFAULT NULL COMMENT 'Estado Muestra',
  `resultado` varchar(45) DEFAULT NULL COMMENT 'Resultado Muestra',
  `tipo1` varchar(45) DEFAULT NULL COMMENT 'Tipo1 Muestra',
  `subtipo1` varchar(45) DEFAULT NULL COMMENT 'Subtipo1 Muestra',
  `tipo2` varchar(45) DEFAULT NULL COMMENT 'Tipo2 Muestra',
  `subtipo2` varchar(45) DEFAULT NULL COMMENT 'Subtipo2 Muestra',
  `comentario_resultado` varchar(45) DEFAULT NULL COMMENT 'Comentarios del resultado',
  PRIMARY KEY (`id_vih_muestra_silab`),
  KEY `fk_vih_form` (`id_vih_form`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla de relacion entre el form VIH y las muestras de labora';

CREATE TABLE `vih_silab_temp` (
  `id_vih_silab_temp` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico de la muestra en SISVIG',
  `MUE_ID` int(11) NOT NULL COMMENT 'Identificador de la muestra en SILAB',
  `MUE_CODIGO_GLOBAL_ANIO` int(11) NOT NULL COMMENT 'Anio de la toma de muestra',
  `MUE_CODIGO_GLOBAL_NUMERO` varchar(45) DEFAULT NULL COMMENT 'Codigo Global de la muestra',
  `IND_PRIMER_NOMBRE` varchar(45) DEFAULT NULL COMMENT 'Primer nombre de la persona',
  `IND_SEGUNDO_NOMBRE` varchar(45) DEFAULT NULL COMMENT 'Segundo nombre de la persona',
  `IND_PRIMER_APELLIDO` varchar(45) DEFAULT NULL COMMENT 'Primer apellido de la persona',
  `IND_SEGUNDO_APELLIDO` varchar(45) DEFAULT NULL COMMENT 'Segundo apellido de la persona',
  `IND_IDENTIFICADOR` varchar(45) DEFAULT NULL COMMENT 'Codigo de identificacion de la persona',
  `IND_IDENTIFICADOR_TIPO` int(11) DEFAULT NULL COMMENT 'Id del tipo de identificacion de la persona',
  `nombre_tipo` varchar(45) DEFAULT NULL COMMENT 'Nombre del tipo de identificacion de la persona',
  `IND_PROC_PROVINCIA` int(11) DEFAULT NULL COMMENT 'Id de la provincia de la persona',
  `IND_PROC_REGION` int(11) DEFAULT NULL COMMENT 'Id de la region de la persona',
  `IND_PROC_DISTRITO` int(11) DEFAULT NULL COMMENT 'Id del distrito de la persona',
  `IND_PROC_CORREGIMIENTO` int(11) DEFAULT NULL COMMENT 'Id del corregimiento de la persona',
  `IND_DIRECCION` varchar(45) DEFAULT NULL COMMENT 'Direccion o punto de referencia de la persona',
  `IND_TELEFONO` varchar(45) DEFAULT NULL COMMENT 'Telefono de la persona',
  `IND_FECHA_NACIMIENTO` varchar(45) DEFAULT NULL COMMENT 'Fecha de nacimiento de la persona',
  `IND_EDAD` int(11) DEFAULT NULL COMMENT 'Edad de la persona',
  `IND_TIPO_EDAD` int(11) DEFAULT NULL COMMENT 'Tipo de edad de la persona',
  `IND_SEXO` varchar(1) DEFAULT NULL COMMENT 'Sexo de la persona M:Hombre y F:Mujer',
  `MUE_FECHA_INICIO` varchar(45) DEFAULT NULL COMMENT 'Fecha de inicio de sintomas',
  `condicion` int(1) DEFAULT NULL COMMENT 'Condicion de la perosna 1:Vivo 2:muerto',
  `MUE_PROC_INST_SALUD` int(11) DEFAULT NULL COMMENT 'Identificador en SILAB de la instalacion de salud',
  `cod_ref_minsa` varchar(45) DEFAULT NULL COMMENT 'Codigo de referencia del MINSA de la instalacion de salud',
  `MUE_OTRO_ESTABLECIMIENTO_NOMBRE` varchar(45) DEFAULT NULL COMMENT 'Nombre de otra instalacion de salud, sino esta en la BD',
  `MUE_REFERIDA_POR` varchar(45) DEFAULT NULL COMMENT 'Nombre del personal de salud que autorizo o solicito la muestra',
  `MUE_FECHA_INGRESO_SISTEMA` varchar(45) DEFAULT NULL COMMENT 'Fecha en que se ingreso la muestra a SILAB - notificacion ',
  `MUE_SEMANA_EPI` int(2) DEFAULT NULL COMMENT 'Semana Epidemiologica en que ingreso la muestra a SILAB',
  PRIMARY KEY (`id_vih_silab_temp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla temporal de las muestras de laborato SILAB';

CREATE TABLE `vih_silab_temp_factor_riesgo` (
  `id_vih_silab_temp_factor_riesgo` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico de la muestra en SISVIG',
  `MUE_ID` int(11) NOT NULL COMMENT 'Identificador de la muestra en SILAB',
  `VP` int(11) DEFAULT NULL COMMENT 'SILAB:Varias Parejas - SISVIG:Hetero promiscuo',
  `TS` int(11) DEFAULT NULL COMMENT 'SILAB:Trabajador sexual - SISVIG:Trabajador sexual',
  `UDI` int(11) DEFAULT NULL COMMENT 'SILAB:Uso de drogas intravenosa - SISVIG:Uso de drogas IV',
  `UDO` int(11) DEFAULT NULL COMMENT 'SILAB:Uso de otras drogas - SISVIG:Uso de drogas no IV',
  `no_preservativo` int(11) DEFAULT NULL COMMENT 'No uso preservativo en su ultima relacion sexual',
  `exp_perinatal` int(11) DEFAULT NULL COMMENT 'SILAB:Exposicion perinatla - SISVIG:Grupo Perinatal - no disponible',
  `desconocido` int(11) DEFAULT NULL COMMENT 'SILAB:desconocido - SISVIG:No especificado',
  `embarazo` int(11) DEFAULT NULL COMMENT 'Si la persona esta en embarazo >1:Si 0:no',
  `donante` int(11) DEFAULT NULL COMMENT 'Si la persona es donante de sangre >1:si 0:no',
  `ITS` int(11) DEFAULT NULL COMMENT 'Si la persona tiene actualmente una ITS >1:si 0:no',
  `transfusion` int(11) DEFAULT NULL COMMENT 'Si la persona tuvo una Transfusion >1:si 0:no',
  `cont_vih` int(11) DEFAULT NULL COMMENT 'SILAB:Contacto VIH - SISVIG:Pareja VIH positiva',
  PRIMARY KEY (`id_vih_silab_temp_factor_riesgo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Tabla temporal de los factores de riesgo de las muestras de ';

CREATE TABLE `vih_tarv` (
  `id_vih_tarv` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador del formulario de TARV',
  `id_vih_form` int(11) NOT NULL COMMENT 'Identificador del formulario de VIH/SIDA',
  `tarv_fec_ingreso` date DEFAULT NULL COMMENT 'Fecha de ingreso a la clinica TARV',
  `id_clinica_tarv` int(11) DEFAULT NULL COMMENT 'Identificador de la clinica TARV',
  `tarv_fec_inicio` date DEFAULT NULL COMMENT 'Fecha de inicio del TARV',
  `tarv_fec_cd4` date DEFAULT NULL COMMENT 'Fecha primera prueba cd4',
  `tarv_res_cd4` int(3) DEFAULT NULL COMMENT '3 digitos Resultado de la primera prueba cd4',
  `tarv_fec_cd4_350` date DEFAULT NULL COMMENT 'Fecha recuento de cd4 <350',
  `tarv_res_cd4_350` int(3) DEFAULT NULL COMMENT '3 digitos Resultado recuento de cd4 <350',
  `tarv_fec_cd4_200` date DEFAULT NULL COMMENT 'Fecha recuento de cd4 <200',
  `tarv_res_cd4_200` int(3) DEFAULT NULL COMMENT '3 digitos Resultado recuento de cd4 <200',
  `tarv_fec_carga_viral` date DEFAULT NULL COMMENT 'Fecha primera carga viral',
  `tarv_res_carga_viral` int(3) DEFAULT NULL COMMENT '3 digitos Resultado primera carga viral',
  `tarv_fec_carga_viral_reciente` date DEFAULT NULL,
  `tarv_res_carga_viral_reciente` int(3) DEFAULT NULL,
  PRIMARY KEY (`id_vih_tarv`),
  UNIQUE KEY `uk_vih_form_tarv_form` (`id_vih_tarv`,`id_vih_form`),
  KEY `fk_vih_tarv_vih_form` (`id_vih_form`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Tabla de rel del formnualario de VIH/SIDA con el formulario ';

